### PR TITLE
Prepare for 1.1.0 release

### PR DESCRIPTION
**Pull request by tsalo**
Closes none.

## Changes proposed in this pull request

- Update the CITATION.cff and HISTORY files with release info for 1.1.0.

### CODE REVIEW

**Review by mattcieslak — APPROVED** [review]
looks good!

**Comment by tsalo** [comment]
Are you happy with the added "Citing CuBIDS" section of the README?

**Comment by mattcieslak** [comment]
Is there a way to make citing the zenodo much easier?

**Comment by tsalo** [comment]
Not really. The new DOI only gets created _after_ each release, so we can't include it in the docs.

**Comment by tsalo** [comment]
Normally we'd have a badge in the README linking to the Zenodo page. I'll add them.

**Comment by tsalo** [comment]
Here's the updated badge section in the RTD:

image

@mattcieslak WDYT?

**Pull request merged**
