### PR TITLE
Make CLI commands available as `cubids <command>`

### PR DESCRIPTION
**Pull request by tsalo**
This builds off of #266, so that should be addressed first.

Changes proposed:

- Reorganize the command-line interfaces so taht there is a central `cubids` command (which we can call `--version` and `--help` on), with each of the regular commands as subcommands.
- Deprecate the original commands.
    - For example, you can call `cubids apply` _and_ `cubids-apply`, but `cubids-apply` will raise a deprecation warning.
- Use the sphinx-argparse extension to autodoc the command line interfaces in the documentation.

### CODE REVIEW

**Comment by tsalo** [comment]
Here's what the CLI documentation looks like: https://cubids--268.org.readthedocs.build/en/268/usage.html#command-line-tools

**Comment by tsalo** [comment]
I'm not sure that the PyPi deployment job will succeed, but I can address that in a followup PR.

**Review by mattcieslak — APPROVED** [review]
This is fantastic, thank you!!

**Comment by tsalo** [comment]
Thanks @mattcieslak!

**Pull request merged**
